spring:
  application:
    name: zyplayer-doc-test
#  mvc:
#    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    continue-on-error: true

# 端口和根路劲，main方法启动时需要，放tomcat后以tomcat的配置为准
server:
  port: 8084
  servlet:
    context-path: /zyplayer-doc-test

# 整个文档项目的配置
zyplayer:
  doc:
    # ------zyplayer_doc_manage相关配置------
    manage:
      elasticsearch:
        # 是否开启es，true或false，现在主要用在wiki文档的搜索，使用的es是6.8.0及以上版本
        open: true
        host: 127.0.0.1
        port: 9300
        cluster-name: zyplayer-doc
      # 管理端的数据库配置
      datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zyplayer_doc_manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
        username: root
        password: root

# 下面的配置可以不用管了
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zyplayer.doc.manage.repository.manage.entity
  typeEnumsPackage:
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

